import type { Metadata } from 'next'
import { Geist, Geist_Mono, Plus_Jakarta_Sans, Playfair_Display } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/global/Navbar'
import Footer from '@/components/global/Footer'
import { cn } from '@/lib/utils'
import { Toaster } from '@/components/ui/sonner'
import { MenuDrawer } from '@/components/global/Navbar/MobileNav'
import NavbarProvider from '@/context/NavbarContext'
import GlobalProviderWrapper from '@/components/Wrapper/GlobalProviderWrapper'
import Cookie from '@/components/global/modals/Cookie'
import Newsletter from '@/components/global/modals/Newsletter'
import ContactModal from '@/components/global/modals/ContactModal'
import ReactQueryProvider from '@/components/Wrapper/ReactQueryProvider'

const jakarta = Plus_Jakarta_Sans({ subsets: ['latin'], variable: '--font-sans' })
const playfair = Playfair_Display({ subsets: ['latin'], variable: '--font-serif' })

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang="en"
      className={cn(
        'h-full',
        'antialiased',
        geistSans.variable,
        geistMono.variable,
        'font-sans',
        jakarta.variable,
        playfair.variable
      )}
    >
      <body className="flex min-h-full flex-col">
        {/* <MenuDrawer /> */}

        <ReactQueryProvider>
          <GlobalProviderWrapper>
            <Toaster />
            <Cookie />
            <ContactModal />
            <Newsletter />

            <NavbarProvider>
              <Navbar />
              <MenuDrawer />
            </NavbarProvider>
            {children}
            <Footer />
          </GlobalProviderWrapper>
        </ReactQueryProvider>
      </body>
    </html>
  )
}
